#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
# and then tuned by Kinesis Team to adjust to Quimera Engine project's needs.  #
#------------------------------------------------------------------------------#

WRKDIR = %cd%

buildDebugLinux32SharedrtStatic: tools_debuglinux32sharedrtstatic

tools_debuglinux32sharedrtstatic: 
	$(MAKE) debuglinux32sharedrtstatic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Tools/Tools-linux.cbp.mak

cleanDebuglinux32SharedrtStatic: clean_tools_debuglinux32sharedrtstatic

clean_tools_debuglinux32sharedrtstatic: 
	$(MAKE) clean_debuglinux32sharedrtstatic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Tools/Tools-linux.cbp.mak

.PHONY: clean_tools_tools

