#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
# and then tuned by Kinesis Team to adjust to Quimera Engine project's needs.  #
#------------------------------------------------------------------------------#

WRKDIR = %cd%

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#	DebugWin32SharedrtStatic   ~~~   DebugWin32SharedrtStatic   ~~~   DebugWin32SharedrtStatic   ~~~   DebugWin32SharedrtStatic   ~~~   DebugWin32SharedrtStatic   ~~~       #  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
	
buildDebugWin32SharedrtStatic: common_debugwin32sharedrtstatic tools_debugwin32sharedrtstatic

tools_debugwin32sharedrtstatic: 
	$(MAKE) debugwin32sharedrtstatic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Tools/Tools-win.cbp.mak

common_debugwin32sharedrtstatic: 
	$(MAKE) debugwin32sharedrtstatic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Common/Common-win.cbp.mak

cleanDebugWin32SharedrtStatic: remove_files_debugwin32sharedrtstatic clean_tools_debugwin32sharedrtstatic clean_common_debugwin32sharedrtstatic
	
remove_files_debugwin32sharedrtstatic:
	cmd /c if exist $(MAKEPATH)\trunk\\testing\\bin\\CodeBlocks10\\DebugWin32SharedrtStatic rmdir $(MAKEPATH)\trunk\\testing\\bin\\CodeBlocks10\\DebugWin32SharedrtStatic /s /q
	cmd /c if exist $(MAKEPATH)\trunk\\testing\\garbage\\CodeBlocks10\\DebugWin32SharedrtStatic rmdir $(MAKEPATH)\trunk\\testing\\garbage\\CodeBlocks10\\DebugWin32SharedrtStatic /s /q

clean_tools_debugwin32sharedrtstatic: 
	$(MAKE) clean_debugwin32sharedrtstatic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Tools/Tools-win.cbp.mak

clean_common_debugwin32sharedrtstatic: 
	$(MAKE) clean_debugwin32sharedrtstatic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Common/Common-win.cbp.mak

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#	DebugWin32SharedrtDynamic   ~~~   DebugWin32SharedrtDynamic   ~~~   DebugWin32SharedrtDynamic   ~~~   DebugWin32SharedrtDynamic   ~~~   DebugWin32SharedrtDynamic   ~~~  #  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------#
	
buildDebugWin32SharedrtDynamic: common_debugwin32sharedrtdynamic tools_debugwin32sharedrtdynamic

tools_debugwin32sharedrtdynamic: 
	$(MAKE) debugwin32sharedrtdynamic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Tools/Tools-win.cbp.mak

common_debugwin32sharedrtdynamic: 
	$(MAKE) debugwin32sharedrtdynamic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Common/Common-win.cbp.mak

cleanDebugWin32SharedrtDynamic: remove_files_debugwin32sharedrtdynamic clean_tools_debugwin32sharedrtdynamic clean_common_debugwin32sharedrtdynamic

remove_files_debugwin32sharedrtdynamic:
	cmd /c if exist $(MAKEPATH)\trunk\\testing\\bin\\CodeBlocks10\\DebugWin32SharedrtDynamic rmdir $(MAKEPATH)\trunk\\testing\\bin\\CodeBlocks10\\DebugWin32SharedrtDynamic /s /q
	cmd /c if exist $(MAKEPATH)\trunk\\testing\\garbage\\CodeBlocks10\\DebugWin32SharedrtDynamic rmdir $(MAKEPATH)\trunk\\testing\\garbage\\CodeBlocks10\\DebugWin32SharedrtDynamic /s /q
	
clean_tools_debugwin32sharedrtdynamic: 
	$(MAKE) clean_debugwin32sharedrtdynamic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Tools/Tools-win.cbp.mak

clean_common_debugwin32sharedrtdynamic: 
	$(MAKE) clean_debugwin32sharedrtdynamic -f $(MAKEPATH)trunk/testing/projects/CodeBlocks10/QEUnitTests/Common/Common-win.cbp.mak

	
.PHONY: buildDebugWin32SharedrtStatic cleanDebugWin32SharedrtStatic buildDebugWin32SharedrtDynamic cleanDebugWin32SharedrtDynamic

