#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.137                       #
# and then tuned by Kinesis Team to adjust to Quimera Engine project's needs.  #
#------------------------------------------------------------------------------#

WRKDIR = %cd%

buildDebugWin32SharedrtStatic: core_debugwin32sharedrtstatic system_debugwin32sharedrtstatic tools_debugwin32sharedrtstatic

core_debugwin32sharedrtstatic:
	$(MAKE) debugwin32sharedrtstatic -f $(MAKEPATH)trunk/projects/CodeBlocks10/QuimeraEngine/Core/Core.cbp.mak MAKEFILE="$(MAKEPATH)" MAKEFILE__="$(MAKEPATH__)"

system_debugwin32sharedrtstatic:
	$(MAKE) debugwin32sharedrtstatic -f $(MAKEPATH)trunk/projects/CodeBlocks10/QuimeraEngine/System/System.cbp.mak MAKEFILE="$(MAKEPATH)" MAKEFILE__="$(MAKEPATH__)"

tools_debugwin32sharedrtstatic:
	$(MAKE) debugwin32sharedrtstatic -f $(MAKEPATH)trunk/projects/CodeBlocks10/QuimeraEngine/Tools/Tools.cbp.mak MAKEFILE="$(MAKEPATH)" MAKEFILE__="$(MAKEPATH__)"
	
cleanDebugWin32SharedrtStatic: clean_core_debugwin32sharedrtstatic clean_system_debugwin32sharedrtstatic clean_tools_debugwin32sharedrtstatic

clean_core_debugwin32sharedrtstatic: 
	$(MAKE) clean_debugwin32sharedrtstatic -f $(MAKEPATH)trunk/projects/CodeBlocks10/QuimeraEngine/Core/Core.cbp.mak

clean_system_debugwin32sharedrtstatic: 
	$(MAKE) clean_debugwin32sharedrtstatic -f $(MAKEPATH)trunk/projects/CodeBlocks10/QuimeraEngine/System/System.cbp.mak

clean_tools_debugwin32sharedrtstatic: 
	$(MAKE) clean_debugwin32sharedrtstatic -f $(MAKEPATH)trunk/projects/CodeBlocks10/QuimeraEngine/Tools/Tools.cbp.mak

.PHONY: clean_core_core clean_system_system clean_tools_tools

