// [TERMS&CONDITIONS]

#ifndef __ITATTESTRESULTLOADER__
#define __ITATTESTRESULTLOADER__

#include <wx/string.h>

#include "TestExecution/TATTestResultNode.h"


namespace Kinesis
{
namespace TestAutomationTool
{
namespace Backend
{

class TATTestResultNode;

/// <summary>
/// Converts a list of test results, whatever the way they are represented, into a test result tree 
/// and stores it.
/// </summary>
class ITATTestResultLoader
{
	// CONSTRUCTORS
	// ---------------
protected:

	/// <summary>
	/// Default constructor.
	/// </summary>
    ITATTestResultLoader(){};


	// DESTRUCTOR
	// ---------------
public:

	/// <summary>
	/// Destructor.
	/// </summary>		
    virtual ~ITATTestResultLoader(){};


	// METHODS
	// ---------------
public:

    /// <summary>
    /// Obtains the test results from the given source and transforms them into test result nodes
    /// of the internally stored tree.
    /// </summary>
    /// <param name="strSource">The source of the test results.</param>
    virtual void Load(const wxString &strSource)=0;

    /// <summary>
    /// Destroys the stored test result tree.
    /// </summary>
    virtual void Clear()=0;


	// PROPERTIES
	// ---------------
public:

    /// <summary>
    /// Gets the test result tree generated by the last load.
    /// </summary>
    /// <returns>
    /// A test result tree.
    /// </returns>
    virtual TATTestResultNode* GetTestResultTree() const=0;


	// ATTRIBUTES
	// ---------------
protected:

    /// <summary>
    /// The test result tree.
    /// </summary>
    TATTestResultNode* m_pTestResultTree;

};

} //namespace Backend
} //namespace TestAutomationTool
} //namespace Kinesis

#endif // __ITATTESTRESULTLOADER__
